services:
  - type: web
    name: plant-disease-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      cd client
      npm install
      npm run build
    startCommand: gunicorn app:app
    envVars:
      - key: PORT
        value: 5000  # Updated the port to match your Flask app (if necessary)
      - key: CUDA_VISIBLE_DEVICES
        value: "-1"  # Add environment variable to disable GPU usage for TensorFlow
