services:
  - type: web
    name: ml-react-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
      cd client
      npm install
      npm run build
    startCommand: gunicorn app:app
    envVars:
      - key: PORT
        value: 5000
